import type { SiteContent } from './types';

/**
 * Default content shipped with the project. The store writes this to
 * `data/site.json` on first boot; after that the admin panel owns the file.
 *
 * Every gradient string below is a literal so Tailwind's content scanner keeps
 * the classes in the production build.
 */

export const GRADIENT_PRESETS = [
  'from-brand-500 via-brand-400 to-aqua-400',
  'from-aqua-500 via-aqua-400 to-brand-400',
  'from-sun-500 via-sun-400 to-rose-400',
  'from-rose-500 via-rose-400 to-brand-400',
  'from-brand-600 via-rose-500 to-sun-400',
  'from-emerald-500 via-aqua-400 to-brand-400',
  'from-indigo-500 via-brand-500 to-rose-400',
  'from-slate-700 via-brand-600 to-aqua-500',
] as const;

export const SEED_CONTENT: SiteContent = {
  version: 1,
  updatedAt: new Date('2026-01-15T09:00:00.000Z').toISOString(),
  brand: {
    name: 'Vibrant School',
    tagline: {
      ru: 'Учебный центр нового поколения',
      uz: 'Yangi avlod o‘quv markazi',
      en: 'A learning center built for what comes next',
    },
    logoMark: 'VS',
  },
  announcement: {
    enabled: true,
    text: {
      ru: 'Набор в весенний поток открыт — осталось 24 места, скидка 20% до 1 марта',
      uz: 'Bahorgi oqimga qabul ochiq — 24 ta joy qoldi, 1-martgacha 20% chegirma',
      en: 'Spring cohort is open — 24 seats left, 20% off until March 1',
    },
    ctaLabel: { ru: 'Забронировать место', uz: 'Joy band qilish', en: 'Reserve a seat' },
    ctaHref: '#apply',
    tone: 'brand',
  },
  nav: {
    links: [
      { id: 'about', label: { ru: 'О центре', uz: 'Markaz haqida', en: 'About' }, href: '#about' },
      { id: 'courses', label: { ru: 'Курсы', uz: 'Kurslar', en: 'Courses' }, href: '#courses' },
      { id: 'methodology', label: { ru: 'Методика', uz: 'Metodika', en: 'Methodology' }, href: '#methodology' },
      { id: 'mentors', label: { ru: 'Преподаватели', uz: 'O‘qituvchilar', en: 'Teachers' }, href: '#mentors' },
      { id: 'reviews', label: { ru: 'Отзывы', uz: 'Sharhlar', en: 'Reviews' }, href: '#reviews' },
      { id: 'contact', label: { ru: 'Контакты', uz: 'Kontaktlar', en: 'Contact' }, href: '#contact' },
    ],
    ctaLabel: { ru: 'Записаться', uz: 'Yozilish', en: 'Enroll now' },
    ctaHref: '#apply',
  },
  hero: {
    scrollHint: { ru: 'Листайте, чтобы пройти путь студента', uz: 'Talaba yo‘lini ko‘rish uchun pastga suring', en: 'Scroll to walk the student journey' },
    stages: [
      {
        id: 'stage-hub',
        badge: { ru: 'Учебный центр · с 2016 года', uz: 'O‘quv markazi · 2016 yildan beri', en: 'Learning center · since 2016' },
        title: { ru: 'Здесь знания', uz: 'Bu yerda bilim', en: 'Where knowledge' },
        highlight: { ru: 'обретают форму', uz: 'shakl topadi', en: 'takes shape' },
        subtitle: {
          ru: 'Vibrant School — это кампус, где IT, языки, точные науки и дизайн живут в одной экосистеме. 12 направлений, 38 менторов, один общий стандарт качества.',
          uz: 'Vibrant School — bu IT, tillar, aniq fanlar va dizayn bitta ekotizimda yashaydigan kampus. 12 ta yo‘nalish, 38 ta mentor, yagona sifat standarti.',
          en: 'Vibrant School is a campus where IT, languages, exact sciences and design live in one ecosystem. 12 tracks, 38 mentors, a single standard of quality.',
        },
        primaryCta: { label: { ru: 'Выбрать курс', uz: 'Kurs tanlash', en: 'Pick a course' }, href: '#courses' },
        secondaryCta: { label: { ru: 'Смотреть методику', uz: 'Metodikani ko‘rish', en: 'See the method' }, href: '#methodology' },
        camera: {
          yaw: -36,
          pitch: 27,
          distance: 31,
          target: { x: 0, y: 1.4, z: 0 },
          fov: 42,
          roll: -1.5,
          lightYaw: 40,
          exposure: 1,
          focus: { hub: 1, desks: 0.28, community: 0.28 },
        },
      },
      {
        id: 'stage-desks',
        badge: { ru: 'Практика · 70% учебного времени', uz: 'Amaliyot · o‘quv vaqtining 70%', en: 'Practice · 70% of class time' },
        title: { ru: 'Не лекции —', uz: 'Ma’ruza emas —', en: 'Not lectures —' },
        highlight: { ru: 'рабочие места', uz: 'ish o‘rinlari', en: 'workstations' },
        subtitle: {
          ru: 'Каждое занятие начинается с задачи, а не со слайда. Студенты пишут код, спорят на английском и разбирают олимпиадные задачи за реальными столами, а не за партами.',
          uz: 'Har bir dars slayd bilan emas, masala bilan boshlanadi. Talabalar kod yozadi, ingliz tilida bahslashadi va olimpiada masalalarini partada emas, haqiqiy ish stolida yechadi.',
          en: 'Every session starts with a problem, not a slide. Students ship code, argue in English and break down olympiad problems at real desks, not school benches.',
        },
        primaryCta: { label: { ru: 'Пробный урок', uz: 'Sinov darsi', en: 'Book a trial' }, href: '#apply' },
        secondaryCta: { label: { ru: 'Программа обучения', uz: 'O‘quv dasturi', en: 'View curriculum' }, href: '#courses' },
        camera: {
          yaw: 41,
          pitch: 10,
          distance: 12.5,
          target: { x: -6.4, y: 1.5, z: 2.2 },
          fov: 34,
          roll: 2,
          lightYaw: 152,
          exposure: 1.14,
          focus: { hub: 0.2, desks: 1, community: 0.14 },
        },
      },
      {
        id: 'stage-community',
        badge: { ru: 'Результат · 94% доходят до конца', uz: 'Natija · 94% oxirigacha yetadi', en: 'Outcome · 94% completion rate' },
        title: { ru: 'Сообщество, которое', uz: 'Oldinga yetaklaydigan', en: 'A community that' },
        highlight: { ru: 'двигает вперёд', uz: 'hamjamiyat', en: 'pushes you forward' },
        subtitle: {
          ru: '2 400 выпускников, 180 поступивших в топовые вузы и Alumni-чат, который работает лучше любого карьерного центра.',
          uz: '2 400 bitiruvchi, top oliygohlarga kirgan 180 nafar talaba va istalgan karyera markazidan yaxshiroq ishlaydigan Alumni-chat.',
          en: '2,400 graduates, 180 admissions to top universities and an alumni network that outperforms any career office.',
        },
        primaryCta: { label: { ru: 'Истории студентов', uz: 'Talabalar hikoyalari', en: 'Student stories' }, href: '#reviews' },
        secondaryCta: { label: { ru: 'Наши менторы', uz: 'Bizning mentorlar', en: 'Meet the mentors' }, href: '#mentors' },
        camera: {
          yaw: 129,
          pitch: 21,
          distance: 18,
          target: { x: 6.2, y: 4.4, z: -4.2 },
          fov: 38,
          roll: -3,
          lightYaw: 250,
          exposure: 1.06,
          focus: { hub: 0.3, desks: 0.14, community: 1 },
        },
      },
      {
        id: 'stage-invite',
        badge: { ru: 'Весенний поток · старт 3 марта', uz: 'Bahorgi oqim · 3-martda boshlanadi', en: 'Spring cohort · starts March 3' },
        title: { ru: 'Ваше место', uz: 'Sizning joyingiz', en: 'Your seat is' },
        highlight: { ru: 'уже готово', uz: 'allaqachon tayyor', en: 'already waiting' },
        subtitle: {
          ru: 'Группы до 12 человек, персональный ментор и план на 3 месяца вперёд. Оставьте заявку — подберём направление за один звонок.',
          uz: '12 kishigacha bo‘lgan guruhlar, shaxsiy mentor va 3 oyga mo‘ljallangan reja. Ariza qoldiring — yo‘nalishni bitta qo‘ng‘iroqda tanlaymiz.',
          en: 'Groups of up to 12, a personal mentor and a plan for the next three months. Leave a request — we will match your track in a single call.',
        },
        primaryCta: { label: { ru: 'Оставить заявку', uz: 'Ariza qoldirish', en: 'Apply now' }, href: '#apply' },
        secondaryCta: { label: { ru: 'Связаться с нами', uz: 'Biz bilan bog‘lanish', en: 'Talk to us' }, href: '#contact' },
        camera: {
          yaw: 208,
          pitch: 33,
          distance: 34,
          target: { x: 0, y: 2.6, z: 0 },
          fov: 46,
          roll: 0,
          lightYaw: 20,
          exposure: 0.97,
          focus: { hub: 0.85, desks: 0.5, community: 0.6 },
        },
      },
    ],
  },
  courses: {
    eyebrow: { ru: 'Каталог', uz: 'Katalog', en: 'Catalog' },
    title: { ru: '12 направлений — один стандарт', uz: '12 ta yo‘nalish — yagona standart', en: '12 tracks — one standard' },
    subtitle: {
      ru: 'Выберите дисциплину, уровень и формат. Каждая программа заканчивается защитой проекта или сертификационным экзаменом.',
      uz: 'Fan, daraja va formatni tanlang. Har bir dastur loyiha himoyasi yoki sertifikat imtihoni bilan yakunlanadi.',
      en: 'Pick a discipline, a level and a format. Every program ends with a project defense or a certification exam.',
    },
    categories: [
      { id: 'it', label: { ru: 'IT и код', uz: 'IT va kod', en: 'IT & Coding' }, icon: 'Code2', accent: 'brand' },
      { id: 'languages', label: { ru: 'Языки', uz: 'Tillar', en: 'Languages' }, icon: 'Languages', accent: 'aqua' },
      { id: 'math', label: { ru: 'Точные науки', uz: 'Aniq fanlar', en: 'Exact sciences' }, icon: 'Sigma', accent: 'sun' },
      { id: 'creative', label: { ru: 'Дизайн', uz: 'Dizayn', en: 'Creative & Design' }, icon: 'Palette', accent: 'rose' },
    ],
    items: [
      {
        id: 'frontend-pro',
        title: { ru: 'Frontend с нуля до Junior', uz: 'Frontend: noldan Juniorgacha', en: 'Frontend: zero to Junior' },
        summary: {
          ru: 'HTML, CSS, JavaScript и React. Восемь проектов в портфолио и защита финального SPA.',
          uz: 'HTML, CSS, JavaScript va React. Portfelda sakkizta loyiha va yakuniy SPA himoyasi.',
          en: 'HTML, CSS, JavaScript and React. Eight portfolio projects and a final SPA defense.',
        },
        description: {
          ru: 'Полный маршрут до первой работы: вёрстка по макету, JavaScript без магии, React с хуками и state-менеджментом, Git-флоу как в командах. Последний месяц — работа в парах над клиентским проектом и подготовка к техническому интервью.',
          uz: 'Birinchi ishgacha to‘liq yo‘l: maket bo‘yicha verstka, sehrsiz JavaScript, hook va state-menejmentli React, jamoalardagidek Git-flow. Oxirgi oy — juftlikda mijoz loyihasi ustida ishlash va texnik intervyuga tayyorgarlik.',
          en: 'The full route to a first job: pixel-accurate markup, JavaScript without magic, React with hooks and state management, a real team Git flow. The final month is pair work on a client project plus technical interview prep.',
        },
        category: 'it',
        level: 'beginner',
        durationMonths: 9,
        hoursPerWeek: 8,
        price: 1290000,
        oldPrice: 1590000,
        currency: 'UZS',
        badge: 'popular',
        mentorIds: ['m-aziz', 'm-dilnoza'],
        outcomes: [
          { ru: 'Портфолио из 8 проектов на GitHub', uz: 'GitHub’da 8 ta loyihadan iborat portfel', en: 'A GitHub portfolio with 8 projects' },
          { ru: 'Уверенный React + TypeScript', uz: 'Ishonchli React + TypeScript', en: 'Confident React + TypeScript' },
          { ru: 'Подготовка к техническому интервью', uz: 'Texnik intervyuga tayyorgarlik', en: 'Technical interview preparation' },
        ],
        gradient: 'from-brand-500 via-brand-400 to-aqua-400',
        seats: 14,
        seatsTaken: 11,
        published: true,
        order: 1,
      },
      {
        id: 'python-data',
        title: { ru: 'Python и Data Science', uz: 'Python va Data Science', en: 'Python & Data Science' },
        summary: {
          ru: 'От синтаксиса до ML-моделей: pandas, визуализация, регрессии и первый Kaggle.',
          uz: 'Sintaksisdan ML-modellargacha: pandas, vizualizatsiya, regressiyalar va birinchi Kaggle.',
          en: 'From syntax to ML models: pandas, visualization, regressions and a first Kaggle run.',
        },
        description: {
          ru: 'Курс для тех, кто хочет работать с данными: чистый Python, pandas и numpy, статистика без формул ради формул, визуализация в matplotlib и plotly, классические ML-модели. Финал — исследование на реальном датасете и защита выводов перед менторами.',
          uz: 'Ma’lumotlar bilan ishlamoqchi bo‘lganlar uchun kurs: sof Python, pandas va numpy, amaliy statistika, matplotlib va plotly’da vizualizatsiya, klassik ML-modellar. Yakunda — haqiqiy datasetdagi tadqiqot va xulosalarni mentorlar oldida himoya qilish.',
          en: 'For people who want to work with data: clean Python, pandas and numpy, statistics that stay practical, visualization in matplotlib and plotly, classic ML models. The finale is a study on a real dataset defended in front of mentors.',
        },
        category: 'it',
        level: 'intermediate',
        durationMonths: 7,
        hoursPerWeek: 6,
        price: 1450000,
        currency: 'UZS',
        badge: 'new',
        mentorIds: ['m-timur'],
        outcomes: [
          { ru: 'Аналитический проект на реальных данных', uz: 'Haqiqiy ma’lumotlar asosidagi tahliliy loyiha', en: 'An analytics project on real data' },
          { ru: 'Уверенные pandas, numpy, sklearn', uz: 'Ishonchli pandas, numpy, sklearn', en: 'Confident pandas, numpy, sklearn' },
          { ru: 'Профиль на Kaggle с решениями', uz: 'Yechimlari bilan Kaggle profili', en: 'A Kaggle profile with submissions' },
        ],
        gradient: 'from-indigo-500 via-brand-500 to-rose-400',
        seats: 12,
        seatsTaken: 5,
        published: true,
        order: 2,
      },
      {
        id: 'ielts-intensive',
        title: { ru: 'IELTS Intensive 6.5+', uz: 'IELTS Intensive 6.5+', en: 'IELTS Intensive 6.5+' },
        summary: {
          ru: 'Четыре модуля, еженедельные mock-тесты и разбор каждой письменной работы.',
          uz: 'To‘rt modul, haftalik mock-testlar va har bir yozma ishning tahlili.',
          en: 'Four modules, weekly mock tests and a line-by-line review of every essay.',
        },
        description: {
          ru: 'Интенсив для тех, кому нужен балл в конкретный срок. Стратегии по каждому модулю, банк из 400 заданий, еженедельный полный mock под таймер и персональный фидбек по Writing и Speaking от экзаменаторов с опытом работы в British Council.',
          uz: 'Ballni aniq muddatga olishi kerak bo‘lganlar uchun intensiv. Har bir modul bo‘yicha strategiyalar, 400 ta topshiriqdan iborat bank, taymer ostida haftalik to‘liq mock va British Council tajribasiga ega imtihonchilardan Writing va Speaking bo‘yicha shaxsiy fikr-mulohaza.',
          en: 'An intensive for people who need a score by a deadline. Per-module strategies, a bank of 400 tasks, a weekly timed full mock and personal Writing and Speaking feedback from examiners with British Council experience.',
        },
        category: 'languages',
        level: 'intermediate',
        durationMonths: 4,
        hoursPerWeek: 8,
        price: 1150000,
        oldPrice: 1350000,
        currency: 'UZS',
        badge: 'popular',
        mentorIds: ['m-kamila', 'm-james'],
        outcomes: [
          { ru: 'Средний прирост +1.5 балла', uz: 'O‘rtacha +1.5 ball o‘sish', en: 'Average gain of +1.5 band' },
          { ru: '16 полных mock-тестов', uz: '16 ta to‘liq mock-test', en: '16 full mock tests' },
          { ru: 'Разбор Writing от экзаменатора', uz: 'Imtihonchidan Writing tahlili', en: 'Examiner-level Writing feedback' },
        ],
        gradient: 'from-aqua-500 via-aqua-400 to-brand-400',
        seats: 16,
        seatsTaken: 14,
        published: true,
        order: 3,
      },
      {
        id: 'speaking-club',
        title: { ru: 'Speaking Club B1–C1', uz: 'Speaking Club B1–C1', en: 'Speaking Club B1–C1' },
        summary: {
          ru: 'Разговорная практика в группах до 8 человек с носителем языка каждую неделю.',
          uz: '8 kishigacha guruhlarda suhbat amaliyoti, har hafta ona tili sohibi bilan.',
          en: 'Conversation practice in groups of up to 8, with a native speaker every week.',
        },
        description: {
          ru: 'Три занятия в неделю без учебников: дебаты, презентации, ролевые интервью и разбор произношения. Раз в неделю — сессия с носителем языка и запись собственного выступления с последующим разбором.',
          uz: 'Haftasiga uchta darslikdan xoli mashg‘ulot: debatlar, prezentatsiyalar, rolli intervyular va talaffuz tahlili. Haftada bir marta — ona tili sohibi bilan sessiya va o‘z chiqishini yozib olib, keyin tahlil qilish.',
          en: 'Three textbook-free sessions a week: debates, presentations, role-play interviews and pronunciation work. Once a week a native-speaker session plus a recorded talk that gets reviewed together.',
        },
        category: 'languages',
        level: 'beginner',
        durationMonths: 5,
        hoursPerWeek: 5,
        price: 890000,
        currency: 'UZS',
        badge: 'none',
        mentorIds: ['m-james'],
        outcomes: [
          { ru: 'Свободная речь на бытовые и рабочие темы', uz: 'Kundalik va ish mavzularida erkin nutq', en: 'Fluent speech on everyday and work topics' },
          { ru: 'Поставленное произношение', uz: 'To‘g‘ri qo‘yilgan talaffuz', en: 'Corrected pronunciation' },
          { ru: 'Опыт публичных выступлений', uz: 'Ommaviy chiqishlar tajribasi', en: 'Public speaking experience' },
        ],
        gradient: 'from-emerald-500 via-aqua-400 to-brand-400',
        seats: 8,
        seatsTaken: 6,
        published: true,
        order: 4,
      },
      {
        id: 'math-olympiad',
        title: { ru: 'Олимпиадная математика', uz: 'Olimpiada matematikasi', en: 'Olympiad Mathematics' },
        summary: {
          ru: 'Комбинаторика, теория чисел и геометрия на уровне республиканских туров.',
          uz: 'Kombinatorika, sonlar nazariyasi va geometriya respublika bosqichi darajasida.',
          en: 'Combinatorics, number theory and geometry at national-round level.',
        },
        description: {
          ru: 'Программа для школьников 8–11 классов, нацеленная на призовые места. Разбор задач прошлых лет, техники доказательств, еженедельные контрольные туры и индивидуальная траектория по слабым темам.',
          uz: '8–11-sinf o‘quvchilari uchun sovrinli o‘rinlarga qaratilgan dastur. O‘tgan yillar masalalari tahlili, isbot texnikalari, haftalik nazorat turlari va zaif mavzular bo‘yicha individual yo‘l xaritasi.',
          en: 'A program for grades 8–11 aimed at podium finishes. Past-paper analysis, proof techniques, weekly timed rounds and an individual track for weak topics.',
        },
        category: 'math',
        level: 'advanced',
        durationMonths: 8,
        hoursPerWeek: 6,
        price: 1090000,
        currency: 'UZS',
        badge: 'limited',
        mentorIds: ['m-shohruh'],
        outcomes: [
          { ru: 'Подготовка к республиканскому туру', uz: 'Respublika bosqichiga tayyorgarlik', en: 'Preparation for the national round' },
          { ru: 'Техники доказательств и оценок', uz: 'Isbot va baholash texnikalari', en: 'Proof and estimation techniques' },
          { ru: '200+ разобранных олимпиадных задач', uz: '200+ tahlil qilingan olimpiada masalasi', en: '200+ olympiad problems solved' },
        ],
        gradient: 'from-sun-500 via-sun-400 to-rose-400',
        seats: 10,
        seatsTaken: 9,
        published: true,
        order: 5,
      },
      {
        id: 'exam-prep',
        title: { ru: 'Физика и математика для поступления', uz: 'Kirish uchun fizika va matematika', en: 'Physics & Maths for admissions' },
        summary: {
          ru: 'Двухпредметная подготовка к вступительным с еженедельным пробным тестированием.',
          uz: 'Haftalik sinov testlari bilan ikki fanli kirish imtihonlariga tayyorgarlik.',
          en: 'Two-subject admissions prep with a weekly full mock exam.',
        },
        description: {
          ru: 'Системная подготовка к вступительным экзаменам: полная программа по обоим предметам, банк из 3 000 задач, еженедельный пробный тест в формате экзамена и подробная аналитика прогресса для родителей.',
          uz: 'Kirish imtihonlariga tizimli tayyorgarlik: ikkala fan bo‘yicha to‘liq dastur, 3 000 ta masaladan iborat bank, imtihon formatidagi haftalik sinov testi va ota-onalar uchun batafsil taraqqiyot tahlili.',
          en: 'Systematic admissions preparation: the full syllabus for both subjects, a bank of 3,000 problems, a weekly exam-format mock and detailed progress analytics for parents.',
        },
        category: 'math',
        level: 'intermediate',
        durationMonths: 9,
        hoursPerWeek: 10,
        price: 1390000,
        currency: 'UZS',
        badge: 'none',
        mentorIds: ['m-shohruh', 'm-timur'],
        outcomes: [
          { ru: 'Полное покрытие экзаменационной программы', uz: 'Imtihon dasturini to‘liq qamrab olish', en: 'Full exam syllabus coverage' },
          { ru: '32 пробных экзамена', uz: '32 ta sinov imtihoni', en: '32 mock exams' },
          { ru: 'Отчёты о прогрессе для родителей', uz: 'Ota-onalar uchun taraqqiyot hisobotlari', en: 'Progress reports for parents' },
        ],
        gradient: 'from-slate-700 via-brand-600 to-aqua-500',
        seats: 18,
        seatsTaken: 12,
        published: true,
        order: 6,
      },
      {
        id: 'uiux-figma',
        title: { ru: 'UI/UX дизайн в Figma', uz: 'Figma’da UI/UX dizayn', en: 'UI/UX design in Figma' },
        summary: {
          ru: 'Исследование, прототип, дизайн-система и защита кейса перед реальным заказчиком.',
          uz: 'Tadqiqot, prototip, dizayn-tizim va keysni haqiqiy buyurtmachi oldida himoya qilish.',
          en: 'Research, prototype, design system and a case defense in front of a real client.',
        },
        description: {
          ru: 'От пользовательских интервью до готовой дизайн-системы: карты пути, вайрфреймы, визуальный язык, компоненты и автолейауты, интерактивный прототип. Финальный кейс защищается перед приглашённым продакт-менеджером.',
          uz: 'Foydalanuvchi intervyularidan tayyor dizayn-tizimgacha: yo‘l xaritalari, vayrfreymlar, vizual til, komponentlar va avtomatik joylashuv, interaktiv prototip. Yakuniy keys taklif etilgan produkt-menejer oldida himoya qilinadi.',
          en: 'From user interviews to a finished design system: journey maps, wireframes, visual language, components and auto-layout, an interactive prototype. The final case is defended in front of an invited product manager.',
        },
        category: 'creative',
        level: 'beginner',
        durationMonths: 6,
        hoursPerWeek: 6,
        price: 1190000,
        currency: 'UZS',
        badge: 'popular',
        mentorIds: ['m-dilnoza'],
        outcomes: [
          { ru: 'Три кейса в Behance-портфолио', uz: 'Behance-portfelda uchta keys', en: 'Three cases in a Behance portfolio' },
          { ru: 'Собственная дизайн-система', uz: 'O‘z dizayn-tizimingiz', en: 'Your own design system' },
          { ru: 'Навык защиты решений перед заказчиком', uz: 'Qarorlarni buyurtmachi oldida himoya qilish ko‘nikmasi', en: 'Skill in defending decisions to clients' },
        ],
        gradient: 'from-rose-500 via-rose-400 to-brand-400',
        seats: 14,
        seatsTaken: 8,
        published: true,
        order: 7,
      },
      {
        id: 'motion-3d',
        title: { ru: '3D и моушн-дизайн', uz: '3D va moushn-dizayn', en: '3D & motion design' },
        summary: {
          ru: 'Blender и After Effects: от первого рендера до анимационного ролика для бренда.',
          uz: 'Blender va After Effects: birinchi renderdan brend uchun animatsion rolikgacha.',
          en: 'Blender and After Effects: from a first render to a branded animation reel.',
        },
        description: {
          ru: 'Моделирование, материалы и свет в Blender, композитинг и анимация в After Effects. Курс построен вокруг одного сквозного проекта — 30-секундного ролика для реального бренда, который выходит в шоурил студента.',
          uz: 'Blender’da modellashtirish, materiallar va yorug‘lik, After Effects’da kompozitsiya va animatsiya. Kurs bitta uzluksiz loyiha atrofida qurilgan — haqiqiy brend uchun 30 soniyalik rolik, u talabaning shourilida chiqadi.',
          en: 'Modeling, materials and lighting in Blender, compositing and animation in After Effects. The course is built around one continuous project — a 30-second spot for a real brand that ships in the student showreel.',
        },
        category: 'creative',
        level: 'intermediate',
        durationMonths: 6,
        hoursPerWeek: 7,
        price: 1490000,
        currency: 'UZS',
        badge: 'new',
        mentorIds: ['m-aziz', 'm-kamila'],
        outcomes: [
          { ru: 'Шоурил с финальным роликом', uz: 'Yakuniy rolik bilan shouril', en: 'A showreel with the final spot' },
          { ru: 'Blender: моделинг, свет, рендер', uz: 'Blender: modelling, yorug‘lik, render', en: 'Blender: modeling, lighting, rendering' },
          { ru: 'Композитинг в After Effects', uz: 'After Effects’da kompozitsiya', en: 'Compositing in After Effects' },
        ],
        gradient: 'from-brand-600 via-rose-500 to-sun-400',
        seats: 12,
        seatsTaken: 4,
        published: true,
        order: 8,
      },
    ],
  },
  methodology: {
    eyebrow: { ru: 'Методика', uz: 'Metodika', en: 'Methodology' },
    title: { ru: 'Почему у нас доучиваются', uz: 'Nega bizda o‘qishni oxiriga yetkazishadi', en: 'Why students actually finish' },
    subtitle: {
      ru: 'Мы измеряем не количество часов, а прогресс. Каждые две недели студент видит, что изменилось в его результатах — и что делать дальше.',
      uz: 'Biz soatlarni emas, taraqqiyotni o‘lchaymiz. Har ikki haftada talaba natijalarida nima o‘zgarganini va keyin nima qilish kerakligini ko‘radi.',
      en: 'We measure progress, not hours. Every two weeks a student sees exactly what changed in their results — and what to do next.',
    },
    features: [
      {
        id: 'f-groups',
        title: { ru: 'Группы до 12 человек', uz: '12 kishigacha guruhlar', en: 'Groups of up to 12' },
        description: {
          ru: 'Ментор успевает дойти до каждого на каждом занятии. Никто не отсиживается в последнем ряду.',
          uz: 'Mentor har darsda har bir o‘quvchiga yetib boradi. Hech kim orqa qatorda yashirinib o‘tirmaydi.',
          en: 'The mentor reaches every student in every session. Nobody hides in the back row.',
        },
        icon: 'Users',
        accent: 'brand',
      },
      {
        id: 'f-practice',
        title: { ru: '70% практики', uz: '70% amaliyot', en: '70% practice' },
        description: {
          ru: 'Теория даётся как инструмент к задаче, а не наоборот. Занятие начинается с проблемы.',
          uz: 'Nazariya masalani yechish quroli sifatida beriladi, aksincha emas. Dars muammodan boshlanadi.',
          en: 'Theory arrives as a tool for the problem, never the reverse. Class starts with the problem.',
        },
        icon: 'Wrench',
        accent: 'aqua',
      },
      {
        id: 'f-tracking',
        title: { ru: 'Прогресс в цифрах', uz: 'Raqamlardagi taraqqiyot', en: 'Progress in numbers' },
        description: {
          ru: 'Личный кабинет с метриками по каждой теме и отчётом раз в две недели.',
          uz: 'Har bir mavzu bo‘yicha ko‘rsatkichlar va ikki haftada bir hisobot bilan shaxsiy kabinet.',
          en: 'A personal dashboard with per-topic metrics and a report every two weeks.',
        },
        icon: 'LineChart',
        accent: 'sun',
      },
      {
        id: 'f-mentor',
        title: { ru: 'Личный ментор', uz: 'Shaxsiy mentor', en: 'A personal mentor' },
        description: {
          ru: 'Отдельный человек отвечает за вашу траекторию и выходит на связь, если вы пропали.',
          uz: 'Alohida shaxs sizning yo‘lingiz uchun javob beradi va yo‘qolib qolsangiz o‘zi bog‘lanadi.',
          en: 'One person owns your trajectory and reaches out if you go quiet.',
        },
        icon: 'Compass',
        accent: 'rose',
      },
      {
        id: 'f-projects',
        title: { ru: 'Защита проектов', uz: 'Loyihalar himoyasi', en: 'Project defense' },
        description: {
          ru: 'Курс заканчивается не тестом, а работой, которую можно показать работодателю.',
          uz: 'Kurs test bilan emas, ish beruvchiga ko‘rsatsa bo‘ladigan ish bilan yakunlanadi.',
          en: 'A course ends with work you can show an employer, not with a quiz.',
        },
        icon: 'Presentation',
        accent: 'brand',
      },
      {
        id: 'f-alumni',
        title: { ru: 'Alumni-сообщество', uz: 'Alumni-hamjamiyat', en: 'Alumni network' },
        description: {
          ru: 'Закрытый чат выпускников, где появляются вакансии и совместные проекты.',
          uz: 'Vakansiyalar va qo‘shma loyihalar paydo bo‘ladigan yopiq bitiruvchilar chati.',
          en: 'A private graduate chat where jobs and joint projects show up first.',
        },
        icon: 'Network',
        accent: 'aqua',
      },
    ],
    stats: [
      { id: 's-graduates', label: { ru: 'Выпускников', uz: 'Bitiruvchilar', en: 'Graduates' }, value: 2400, suffix: '+', icon: 'GraduationCap' },
      { id: 's-universities', label: { ru: 'Поступили в топ-вузы', uz: 'Top oliygohlarga kirdi', en: 'Top-university admissions' }, value: 180, suffix: '', icon: 'Landmark' },
      { id: 's-score', label: { ru: 'Средний балл IELTS', uz: 'O‘rtacha IELTS bali', en: 'Average IELTS band' }, value: 7, suffix: '.0', icon: 'Star' },
      { id: 's-completion', label: { ru: 'Доходят до конца', uz: 'Oxirigacha yetadi', en: 'Completion rate' }, value: 94, suffix: '%', icon: 'Trophy' },
    ],
    steps: [
      {
        id: 'p1',
        title: { ru: 'Диагностика', uz: 'Diagnostika', en: 'Diagnostics' },
        description: {
          ru: 'Бесплатный тест и разговор с методистом: определяем реальный уровень и цель.',
          uz: 'Bepul test va metodist bilan suhbat: haqiqiy daraja va maqsadni aniqlaymiz.',
          en: 'A free placement test and a talk with a methodologist to find the real level and the goal.',
        },
      },
      {
        id: 'p2',
        title: { ru: 'План на 3 месяца', uz: '3 oylik reja', en: 'A 90-day plan' },
        description: {
          ru: 'Собираем траекторию с конкретными контрольными точками и датами.',
          uz: 'Aniq nazorat nuqtalari va sanalar bilan yo‘l xaritasini tuzamiz.',
          en: 'We assemble a trajectory with concrete checkpoints and dates.',
        },
      },
      {
        id: 'p3',
        title: { ru: 'Практика и разборы', uz: 'Amaliyot va tahlillar', en: 'Practice and reviews' },
        description: {
          ru: 'Занятия, домашние проекты и еженедельный фидбек от ментора.',
          uz: 'Mashg‘ulotlar, uy loyihalari va mentordan haftalik fikr-mulohaza.',
          en: 'Sessions, home projects and weekly mentor feedback.',
        },
      },
      {
        id: 'p4',
        title: { ru: 'Защита и результат', uz: 'Himoya va natija', en: 'Defense and outcome' },
        description: {
          ru: 'Финальный проект или экзамен, сертификат и помощь с портфолио.',
          uz: 'Yakuniy loyiha yoki imtihon, sertifikat va portfel bo‘yicha yordam.',
          en: 'A final project or exam, a certificate and portfolio support.',
        },
      },
    ],
  },
  mentors: {
    eyebrow: { ru: 'Команда', uz: 'Jamoa', en: 'The team' },
    title: { ru: 'Менторы, а не лекторы', uz: 'Mentorlar, ma’ruzachilar emas', en: 'Mentors, not lecturers' },
    subtitle: {
      ru: 'Все преподаватели совмещают работу в индустрии с обучением — поэтому программы обновляются каждый поток.',
      uz: 'Barcha o‘qituvchilar sohadagi ishni o‘qitish bilan birga olib boradi — shuning uchun dasturlar har oqimda yangilanadi.',
      en: 'Every teacher combines industry work with teaching — which is why the programs are refreshed every cohort.',
    },
    items: [
      {
        id: 'm-aziz',
        name: 'Aziz Rakhimov',
        role: { ru: 'Ведущий Frontend-ментор', uz: 'Yetakchi Frontend-mentor', en: 'Lead Frontend mentor' },
        bio: {
          ru: 'Восемь лет в продуктовой разработке, последние три — тимлид в финтех-компании. Собрал программу Frontend с нуля и довёл 11 потоков.',
          uz: 'Produkt ishlab chiqishda sakkiz yil, so‘nggi uch yili fintex kompaniyasida timlid. Frontend dasturini noldan tuzgan va 11 ta oqimni yakunlagan.',
          en: 'Eight years in product engineering, the last three as a fintech team lead. Built the Frontend track from scratch and has run 11 cohorts.',
        },
        initials: 'AR',
        gradient: 'from-brand-500 via-brand-400 to-aqua-400',
        qualifications: [
          { ru: 'Team Lead, финтех-платформа', uz: 'Team Lead, fintex platforma', en: 'Team Lead, fintech platform' },
          { ru: 'Спикер FrontendConf 2024', uz: 'FrontendConf 2024 spikeri', en: 'Speaker, FrontendConf 2024' },
        ],
        yearsExperience: 8,
        studentsTaught: 420,
        socials: { telegram: 'https://t.me/vibrantschool', github: 'https://github.com', linkedin: 'https://linkedin.com' },
        published: true,
        order: 1,
      },
      {
        id: 'm-kamila',
        name: 'Kamila Yusupova',
        role: { ru: 'Экзаменатор IELTS, методист', uz: 'IELTS imtihonchisi, metodist', en: 'IELTS examiner, methodologist' },
        bio: {
          ru: 'Готовит к IELTS девять лет, работала экзаменатором. Средний прирост её групп — 1.5 балла за четыре месяца.',
          uz: 'To‘qqiz yildan beri IELTS’ga tayyorlaydi, imtihonchi bo‘lib ishlagan. Uning guruhlari o‘rtacha to‘rt oyda 1.5 ball o‘sadi.',
          en: 'Nine years of IELTS preparation, former examiner. Her groups average a 1.5 band gain in four months.',
        },
        initials: 'KY',
        gradient: 'from-aqua-500 via-aqua-400 to-brand-400',
        qualifications: [
          { ru: 'CELTA, Cambridge', uz: 'CELTA, Cambridge', en: 'CELTA, Cambridge' },
          { ru: 'Бывший экзаменатор IELTS', uz: 'Sobiq IELTS imtihonchisi', en: 'Former IELTS examiner' },
        ],
        yearsExperience: 9,
        studentsTaught: 610,
        socials: { telegram: 'https://t.me/vibrantschool', linkedin: 'https://linkedin.com' },
        published: true,
        order: 2,
      },
      {
        id: 'm-shohruh',
        name: 'Shohruh Ergashev',
        role: { ru: 'Тренер олимпиадной сборной', uz: 'Olimpiada terma jamoasi murabbiyi', en: 'Olympiad team coach' },
        bio: {
          ru: 'Кандидат физико-математических наук, тренер городской сборной. Его студенты взяли 27 призовых мест за три года.',
          uz: 'Fizika-matematika fanlari nomzodi, shahar terma jamoasi murabbiyi. Uning o‘quvchilari uch yilda 27 ta sovrinli o‘rinni qo‘lga kiritgan.',
          en: 'PhD in physics and mathematics, coach of the city team. His students have taken 27 podium places in three years.',
        },
        initials: 'SE',
        gradient: 'from-sun-500 via-sun-400 to-rose-400',
        qualifications: [
          { ru: 'PhD, прикладная математика', uz: 'PhD, amaliy matematika', en: 'PhD, applied mathematics' },
          { ru: '27 призёров олимпиад', uz: '27 nafar olimpiada sovrindori', en: '27 olympiad medalists' },
        ],
        yearsExperience: 12,
        studentsTaught: 380,
        socials: { telegram: 'https://t.me/vibrantschool' },
        published: true,
        order: 3,
      },
      {
        id: 'm-dilnoza',
        name: 'Dilnoza Karimova',
        role: { ru: 'Product-дизайнер, ментор UI/UX', uz: 'Produkt-dizayner, UI/UX mentori', en: 'Product designer, UI/UX mentor' },
        bio: {
          ru: 'Ведёт дизайн в маркетплейсе с аудиторией 2 млн пользователей. Учит студентов защищать решения, а не украшать экраны.',
          uz: '2 mln foydalanuvchili marketpleysda dizaynni boshqaradi. Talabalarni ekranni bezashga emas, qarorlarni himoya qilishga o‘rgatadi.',
          en: 'Leads design at a marketplace with 2M users. Teaches students to defend decisions rather than decorate screens.',
        },
        initials: 'DK',
        gradient: 'from-rose-500 via-rose-400 to-brand-400',
        qualifications: [
          { ru: 'Senior Product Designer', uz: 'Senior Product Designer', en: 'Senior Product Designer' },
          { ru: 'Ментор ADPList', uz: 'ADPList mentori', en: 'ADPList mentor' },
        ],
        yearsExperience: 7,
        studentsTaught: 290,
        socials: { telegram: 'https://t.me/vibrantschool', website: 'https://example.com', linkedin: 'https://linkedin.com' },
        published: true,
        order: 4,
      },
      {
        id: 'm-timur',
        name: 'Timur Nazarov',
        role: { ru: 'Data Scientist, ментор Python', uz: 'Data Scientist, Python mentori', en: 'Data Scientist, Python mentor' },
        bio: {
          ru: 'Строит рекомендательные системы в e-commerce. Объясняет статистику так, что её понимают школьники.',
          uz: 'E-commerce’da tavsiya tizimlarini quradi. Statistikani maktab o‘quvchilari ham tushunadigan qilib tushuntiradi.',
          en: 'Builds recommender systems in e-commerce. Explains statistics in a way high-schoolers actually follow.',
        },
        initials: 'TN',
        gradient: 'from-indigo-500 via-brand-500 to-rose-400',
        qualifications: [
          { ru: 'MSc, Data Science', uz: 'MSc, Data Science', en: 'MSc, Data Science' },
          { ru: 'Kaggle Expert', uz: 'Kaggle Expert', en: 'Kaggle Expert' },
        ],
        yearsExperience: 6,
        studentsTaught: 210,
        socials: { github: 'https://github.com', linkedin: 'https://linkedin.com' },
        published: true,
        order: 5,
      },
      {
        id: 'm-james',
        name: 'James Whitfield',
        role: { ru: 'Носитель языка, Speaking Club', uz: 'Ona tili sohibi, Speaking Club', en: 'Native speaker, Speaking Club' },
        bio: {
          ru: 'Из Манчестера, шесть лет преподаёт разговорный английский. Ведёт дебаты и ставит произношение.',
          uz: 'Manchesterdan, olti yildan beri so‘zlashuv ingliz tilini o‘qitadi. Debatlarni olib boradi va talaffuzni to‘g‘rilaydi.',
          en: 'From Manchester, six years teaching conversational English. Runs the debates and fixes pronunciation.',
        },
        initials: 'JW',
        gradient: 'from-emerald-500 via-aqua-400 to-brand-400',
        qualifications: [
          { ru: 'TESOL Certified', uz: 'TESOL Certified', en: 'TESOL Certified' },
          { ru: 'Носитель языка (UK)', uz: 'Ona tili sohibi (UK)', en: 'Native speaker (UK)' },
        ],
        yearsExperience: 6,
        studentsTaught: 340,
        socials: { telegram: 'https://t.me/vibrantschool' },
        published: true,
        order: 6,
      },
    ],
  },
  reviews: {
    eyebrow: { ru: 'Отзывы', uz: 'Sharhlar', en: 'Reviews' },
    title: { ru: 'Результаты, которые можно проверить', uz: 'Tekshirib ko‘rsa bo‘ladigan natijalar', en: 'Results you can verify' },
    subtitle: {
      ru: 'Мы показываем метрики до и после — от балла IELTS до первой зарплаты в IT.',
      uz: 'Biz oldin va keyingi ko‘rsatkichlarni ko‘rsatamiz — IELTS balidan IT’dagi birinchi maoshgacha.',
      en: 'We show the before and after — from an IELTS band to a first salary in tech.',
    },
    items: [
      {
        id: 'r-1',
        author: 'Nilufar A.',
        authorRole: { ru: 'Выпускница Frontend, 2025', uz: 'Frontend bitiruvchisi, 2025', en: 'Frontend graduate, 2025' },
        quote: {
          ru: 'Пришла без единой строчки кода, а через девять месяцев получила оффер джуниором. Больше всего помогли парные проекты — на них я перестала бояться чужого кода.',
          uz: 'Bitta ham kod satrisiz keldim, to‘qqiz oydan keyin junior lavozimiga taklif oldim. Eng ko‘p juftlikdagi loyihalar yordam berdi — o‘shalarda birovning kodidan qo‘rqishni bas qildim.',
          en: 'I arrived without a single line of code and had a junior offer nine months later. The pair projects helped most — that is where I stopped fearing other people’s code.',
        },
        initials: 'NA',
        gradient: 'from-brand-500 via-brand-400 to-aqua-400',
        rating: 5,
        metric: { label: { ru: 'Первый оффер', uz: 'Birinchi taklif', en: 'First offer' }, before: '0 опыта', after: 'Junior Frontend' },
        courseId: 'frontend-pro',
        featured: true,
        published: true,
        order: 1,
      },
      {
        id: 'r-2',
        author: 'Bekzod T.',
        authorRole: { ru: 'IELTS Intensive, 2025', uz: 'IELTS Intensive, 2025', en: 'IELTS Intensive, 2025' },
        quote: {
          ru: 'Два раза сдавал сам и застревал на 5.5. Здесь за четыре месяца разобрали каждую ошибку в Writing — получил 7.0 с первой попытки после курса.',
          uz: 'Ikki marta o‘zim topshirdim va 5.5 da qotib qoldim. Bu yerda to‘rt oyda Writing’dagi har bir xatoni tahlil qildik — kursdan keyin birinchi urinishda 7.0 oldim.',
          en: 'I took the test twice on my own and got stuck at 5.5. Here we dissected every Writing mistake for four months — I got 7.0 on the first attempt after the course.',
        },
        initials: 'BT',
        gradient: 'from-aqua-500 via-aqua-400 to-brand-400',
        rating: 5,
        videoUrl: 'https://www.youtube.com/embed/ysz5S6PUM-U',
        metric: { label: { ru: 'Балл IELTS', uz: 'IELTS bali', en: 'IELTS band' }, before: '5.5', after: '7.0' },
        courseId: 'ielts-intensive',
        featured: true,
        published: true,
        order: 2,
      },
      {
        id: 'r-3',
        author: 'Malika S.',
        authorRole: { ru: 'Олимпиадная математика, 11 класс', uz: 'Olimpiada matematikasi, 11-sinf', en: 'Olympiad Maths, grade 11' },
        quote: {
          ru: 'Шохрух ака объясняет не решение, а способ думать. На республиканском туре я впервые увидела знакомый тип задачи и решила её за десять минут.',
          uz: 'Shohruh aka yechimni emas, fikrlash usulini tushuntiradi. Respublika bosqichida birinchi marta tanish masala turini ko‘rdim va uni o‘n daqiqada yechdim.',
          en: 'Shohruh does not explain solutions, he explains how to think. At the national round I recognized a problem type for the first time and solved it in ten minutes.',
        },
        initials: 'MS',
        gradient: 'from-sun-500 via-sun-400 to-rose-400',
        rating: 5,
        metric: { label: { ru: 'Олимпиада', uz: 'Olimpiada', en: 'Olympiad' }, before: 'Городской тур', after: '2 место, республика' },
        courseId: 'math-olympiad',
        featured: true,
        published: true,
        order: 3,
      },
      {
        id: 'r-4',
        author: 'Jasur K.',
        authorRole: { ru: 'UI/UX дизайн, 2025', uz: 'UI/UX dizayn, 2025', en: 'UI/UX design, 2025' },
        quote: {
          ru: 'Главное, что дал курс, — привычка объяснять каждое решение. На собеседовании меня спрашивали «почему так», и мне было что ответить.',
          uz: 'Kurs bergan eng muhim narsa — har bir qarorni asoslash odati. Suhbatda mendan «nega aynan shunday» deb so‘rashdi va menda javob bor edi.',
          en: 'The main thing the course gave me was the habit of justifying every decision. In interviews they kept asking "why this way", and I had answers.',
        },
        initials: 'JK',
        gradient: 'from-rose-500 via-rose-400 to-brand-400',
        rating: 5,
        metric: { label: { ru: 'Портфолио', uz: 'Portfel', en: 'Portfolio' }, before: '0 кейсов', after: '3 кейса + оффер' },
        courseId: 'uiux-figma',
        featured: false,
        published: true,
        order: 4,
      },
      {
        id: 'r-5',
        author: 'Zarina M.',
        authorRole: { ru: 'Python и Data Science, 2025', uz: 'Python va Data Science, 2025', en: 'Python & Data Science, 2025' },
        quote: {
          ru: 'Работала бухгалтером и хотела в аналитику. Финальный проект по данным нашей же компании стал моим первым рабочим кейсом — и поводом для повышения.',
          uz: 'Buxgalter bo‘lib ishlardim va tahlilga o‘tmoqchi edim. O‘z kompaniyamiz ma’lumotlari bo‘yicha yakuniy loyiha birinchi ish keysim va lavozim ko‘tarilishiga sabab bo‘ldi.',
          en: 'I worked in accounting and wanted to move into analytics. The final project on our own company data became my first work case — and the reason for a promotion.',
        },
        initials: 'ZM',
        gradient: 'from-indigo-500 via-brand-500 to-rose-400',
        rating: 4,
        metric: { label: { ru: 'Позиция', uz: 'Lavozim', en: 'Role' }, before: 'Бухгалтер', after: 'Data Analyst' },
        courseId: 'python-data',
        featured: false,
        published: true,
        order: 5,
      },
    ],
  },
  lead: {
    eyebrow: { ru: 'Заявка', uz: 'Ariza', en: 'Apply' },
    title: { ru: 'Подберём направление за один звонок', uz: 'Yo‘nalishni bitta qo‘ng‘iroqda tanlaymiz', en: 'We will match your track in one call' },
    subtitle: {
      ru: 'Оставьте контакты — методист свяжется в течение рабочего дня, проведёт диагностику и предложит план.',
      uz: 'Kontaktlaringizni qoldiring — metodist ish kuni davomida bog‘lanadi, diagnostika o‘tkazadi va reja taklif qiladi.',
      en: 'Leave your contacts — a methodologist calls within one business day, runs the diagnostics and proposes a plan.',
    },
    successTitle: { ru: 'Заявка принята', uz: 'Ariza qabul qilindi', en: 'Application received' },
    successBody: {
      ru: 'Мы уже видим вашу заявку. Методист позвонит в течение рабочего дня — обычно быстрее.',
      uz: 'Arizangizni ko‘rib turibmiz. Metodist ish kuni davomida qo‘ng‘iroq qiladi — odatda tezroq.',
      en: 'Your application is in. A methodologist will call within one business day — usually sooner.',
    },
    consent: {
      ru: 'Нажимая кнопку, вы соглашаетесь на обработку персональных данных.',
      uz: 'Tugmani bosish orqali siz shaxsiy ma’lumotlarni qayta ishlashga rozilik bildirasiz.',
      en: 'By submitting you agree to the processing of your personal data.',
    },
  },
  footer: {
    about: {
      ru: 'Vibrant School — учебный центр в Ташкенте: IT, языки, точные науки и дизайн. Работаем с 2016 года.',
      uz: 'Vibrant School — Toshkentdagi o‘quv markazi: IT, tillar, aniq fanlar va dizayn. 2016 yildan beri ishlaymiz.',
      en: 'Vibrant School is a learning center in Tashkent: IT, languages, exact sciences and design. Running since 2016.',
    },
    address: {
      ru: 'Ташкент, ул. Амира Темура 108, 3 этаж',
      uz: 'Toshkent, Amir Temur ko‘chasi 108, 3-qavat',
      en: '108 Amir Temur St., 3rd floor, Tashkent',
    },
    phone: '+998 (71) 200-16-16',
    email: 'hello@vibrant.school',
    mapUrl: 'https://www.openstreetmap.org/?mlat=41.3111&mlon=69.2797#map=16/41.3111/69.2797',
    newsletterTitle: { ru: 'Дайджест раз в месяц', uz: 'Oyiga bir marta dayjest', en: 'A monthly digest' },
    newsletterSubtitle: {
      ru: 'Открытые уроки, дедлайны наборов и разборы задач. Без спама.',
      uz: 'Ochiq darslar, qabul muddatlari va masalalar tahlili. Spamsiz.',
      en: 'Open lessons, cohort deadlines and problem breakdowns. No spam.',
    },
    socials: [
      { id: 'tg', label: 'Telegram', href: 'https://t.me/vibrantschool', icon: 'Send' },
      { id: 'ig', label: 'Instagram', href: 'https://instagram.com', icon: 'Instagram' },
      { id: 'yt', label: 'YouTube', href: 'https://youtube.com', icon: 'Youtube' },
      { id: 'li', label: 'LinkedIn', href: 'https://linkedin.com', icon: 'Linkedin' },
    ],
    columns: [
      {
        id: 'c-learn',
        title: { ru: 'Обучение', uz: 'Ta’lim', en: 'Learning' },
        links: [
          { id: 'l-courses', label: { ru: 'Все курсы', uz: 'Barcha kurslar', en: 'All courses' }, href: '#courses' },
          { id: 'l-method', label: { ru: 'Методика', uz: 'Metodika', en: 'Methodology' }, href: '#methodology' },
          { id: 'l-mentors', label: { ru: 'Преподаватели', uz: 'O‘qituvchilar', en: 'Teachers' }, href: '#mentors' },
          { id: 'l-trial', label: { ru: 'Пробный урок', uz: 'Sinov darsi', en: 'Trial lesson' }, href: '#apply' },
        ],
      },
      {
        id: 'c-center',
        title: { ru: 'Центр', uz: 'Markaz', en: 'Center' },
        links: [
          { id: 'l-about', label: { ru: 'О нас', uz: 'Biz haqimizda', en: 'About us' }, href: '#about' },
          { id: 'l-reviews', label: { ru: 'Отзывы', uz: 'Sharhlar', en: 'Reviews' }, href: '#reviews' },
          { id: 'l-contact', label: { ru: 'Контакты', uz: 'Kontaktlar', en: 'Contact' }, href: '#contact' },
          { id: 'l-careers', label: { ru: 'Вакансии', uz: 'Vakansiyalar', en: 'Careers' }, href: '#contact' },
        ],
      },
    ],
  },
  integrations: {
    telegramEnabled: false,
    emailEnabled: false,
    notifyEmail: 'admissions@vibrant.school',
  },
};
